# Generated by Django 5.0 on 2026-02-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
                ('founded_year', models.IntegerField()),
                ('no_of_trophies', models.IntegerField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('city', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('coach', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'franchises',
            },
        ),
    ]
