# Generated by Django 5.0 on 2026-02-14 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplApp', '0002_alter_franchise_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveBigIntegerField()),
                ('role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All-rounder', 'All-rounder'), ('Wicket-keeper', 'Wicket-keeper')], max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='player_photos/')),
                ('Franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='iplApp.franchise')),
            ],
        ),
    ]
