# Generated by Django 5.0 on 2026-02-16 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplApp', '0003_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplApp.franchise')),
            ],
        ),
    ]
